root = "."
tmp_dir = "tmp"

[build]
  bin = "./tmp/memento"
  cmd = "go build -tags dev -o ./tmp/memento ./cmd/memento"
  delay = 1000
  exclude_dir = ["tmp", "web", "node_modules", "db"]
  exclude_regex = ["_test\.go$"]
  include_ext = ["go", "sql"]
  kill_delay = "0s"
  send_interrupt = false
  stop_on_error = true

[log]
  time = false

[misc]
  clean_on_exit = true
