// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

type Attachment struct {
	ID          int64              `json:"id"`
	MemoID      int64              `json:"memo_id"`
	Filename    string             `json:"filename"`
	ContentType string             `json:"content_type"`
	SizeBytes   int64              `json:"size_bytes"`
	StoragePath string             `json:"storage_path"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type DailyReport struct {
	ID                 int64              `json:"id"`
	ReportDate         pgtype.Date        `json:"report_date"`
	SessionCount       int32              `json:"session_count"`
	TotalMemos         int32              `json:"total_memos"`
	TotalChars         int32              `json:"total_chars"`
	CharsPerMinute     pgtype.Float8      `json:"chars_per_minute"`
	ActiveMinutes      int32              `json:"active_minutes"`
	HourlyDistribution json.RawMessage    `json:"hourly_distribution"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

type Memo struct {
	ID          int64              `json:"id"`
	SessionID   int64              `json:"session_id"`
	Content     string             `json:"content"`
	ContentHtml string             `json:"content_html"`
	Metadata    json.RawMessage    `json:"metadata"`
	Pinned      bool               `json:"pinned"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
}

type MemoTag struct {
	MemoID int64 `json:"memo_id"`
	TagID  int64 `json:"tag_id"`
}

type Session struct {
	ID         int64              `json:"id"`
	StartedAt  pgtype.Timestamptz `json:"started_at"`
	EndedAt    pgtype.Timestamptz `json:"ended_at"`
	DateLabel  pgtype.Date        `json:"date_label"`
	MemoCount  int32              `json:"memo_count"`
	TotalChars int32              `json:"total_chars"`
}

type Tag struct {
	ID        int64              `json:"id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
