// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package repository

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMemo = `-- name: CreateMemo :one
INSERT INTO memos (session_id, content, content_html)
VALUES ($1, $2, $3)
RETURNING id, session_id, content, content_html, metadata, pinned, created_at, updated_at, deleted_at
`

type CreateMemoParams struct {
	SessionID   int64  `json:"session_id"`
	Content     string `json:"content"`
	ContentHtml string `json:"content_html"`
}

func (q *Queries) CreateMemo(ctx context.Context, arg CreateMemoParams) (Memo, error) {
	row := q.db.QueryRow(ctx, createMemo, arg.SessionID, arg.Content, arg.ContentHtml)
	var i Memo
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Content,
		&i.ContentHtml,
		&i.Metadata,
		&i.Pinned,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createMemoTag = `-- name: CreateMemoTag :exec
INSERT INTO memo_tags (memo_id, tag_id) VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type CreateMemoTagParams struct {
	MemoID int64 `json:"memo_id"`
	TagID  int64 `json:"tag_id"`
}

func (q *Queries) CreateMemoTag(ctx context.Context, arg CreateMemoTagParams) error {
	_, err := q.db.Exec(ctx, createMemoTag, arg.MemoID, arg.TagID)
	return err
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (started_at, ended_at, date_label, memo_count, total_chars)
VALUES ($1, $1, $2, 0, 0)
RETURNING id, started_at, ended_at, date_label, memo_count, total_chars
`

type CreateSessionParams struct {
	StartedAt pgtype.Timestamptz `json:"started_at"`
	DateLabel pgtype.Date        `json:"date_label"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession, arg.StartedAt, arg.DateLabel)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.StartedAt,
		&i.EndedAt,
		&i.DateLabel,
		&i.MemoCount,
		&i.TotalChars,
	)
	return i, err
}

const deleteMemoTags = `-- name: DeleteMemoTags :exec
DELETE FROM memo_tags WHERE memo_id = $1
`

func (q *Queries) DeleteMemoTags(ctx context.Context, memoID int64) error {
	_, err := q.db.Exec(ctx, deleteMemoTags, memoID)
	return err
}

const finalizeSession = `-- name: FinalizeSession :exec
UPDATE sessions SET ended_at = $2 WHERE id = $1
`

type FinalizeSessionParams struct {
	ID      int64              `json:"id"`
	EndedAt pgtype.Timestamptz `json:"ended_at"`
}

func (q *Queries) FinalizeSession(ctx context.Context, arg FinalizeSessionParams) error {
	_, err := q.db.Exec(ctx, finalizeSession, arg.ID, arg.EndedAt)
	return err
}

const getActiveSession = `-- name: GetActiveSession :one
SELECT id, started_at, ended_at, date_label, memo_count, total_chars
FROM sessions
ORDER BY started_at DESC
LIMIT 1
FOR UPDATE
`

// Get the most recent session that could still be active (FOR UPDATE lock)
func (q *Queries) GetActiveSession(ctx context.Context) (Session, error) {
	row := q.db.QueryRow(ctx, getActiveSession)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.StartedAt,
		&i.EndedAt,
		&i.DateLabel,
		&i.MemoCount,
		&i.TotalChars,
	)
	return i, err
}

const getDailyReport = `-- name: GetDailyReport :one
SELECT id, report_date, session_count, total_memos, total_chars,
       chars_per_minute, active_minutes, hourly_distribution, created_at
FROM daily_reports
WHERE report_date = $1
`

func (q *Queries) GetDailyReport(ctx context.Context, reportDate pgtype.Date) (DailyReport, error) {
	row := q.db.QueryRow(ctx, getDailyReport, reportDate)
	var i DailyReport
	err := row.Scan(
		&i.ID,
		&i.ReportDate,
		&i.SessionCount,
		&i.TotalMemos,
		&i.TotalChars,
		&i.CharsPerMinute,
		&i.ActiveMinutes,
		&i.HourlyDistribution,
		&i.CreatedAt,
	)
	return i, err
}

const getDailySummary = `-- name: GetDailySummary :many
SELECT id, started_at, ended_at, date_label, memo_count, total_chars
FROM sessions
WHERE date_label = $1
ORDER BY started_at
`

func (q *Queries) GetDailySummary(ctx context.Context, dateLabel pgtype.Date) ([]Session, error) {
	rows, err := q.db.Query(ctx, getDailySummary, dateLabel)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.StartedAt,
			&i.EndedAt,
			&i.DateLabel,
			&i.MemoCount,
			&i.TotalChars,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFinalizedSessions = `-- name: GetFinalizedSessions :many
SELECT id, started_at, ended_at, date_label, memo_count, total_chars
FROM sessions
WHERE ended_at < $1
ORDER BY date_label
`

// Sessions whose ended_at + gap threshold is before now (i.e., finalized)
func (q *Queries) GetFinalizedSessions(ctx context.Context, threshold pgtype.Timestamptz) ([]Session, error) {
	rows, err := q.db.Query(ctx, getFinalizedSessions, threshold)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.StartedAt,
			&i.EndedAt,
			&i.DateLabel,
			&i.MemoCount,
			&i.TotalChars,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getHeatmapData = `-- name: GetHeatmapData :many
SELECT date_label, SUM(memo_count)::int AS memo_count, SUM(total_chars)::int AS total_chars
FROM sessions
WHERE date_label >= $1 AND date_label <= $2
GROUP BY date_label
ORDER BY date_label
`

type GetHeatmapDataParams struct {
	FromDate pgtype.Date `json:"from_date"`
	ToDate   pgtype.Date `json:"to_date"`
}

type GetHeatmapDataRow struct {
	DateLabel  pgtype.Date `json:"date_label"`
	MemoCount  int32       `json:"memo_count"`
	TotalChars int32       `json:"total_chars"`
}

func (q *Queries) GetHeatmapData(ctx context.Context, arg GetHeatmapDataParams) ([]GetHeatmapDataRow, error) {
	rows, err := q.db.Query(ctx, getHeatmapData, arg.FromDate, arg.ToDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetHeatmapDataRow{}
	for rows.Next() {
		var i GetHeatmapDataRow
		if err := rows.Scan(&i.DateLabel, &i.MemoCount, &i.TotalChars); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMemo = `-- name: GetMemo :one
SELECT m.id, m.session_id, m.content, m.content_html, m.metadata, m.pinned,
       m.created_at, m.updated_at, m.deleted_at
FROM memos m
WHERE m.id = $1
`

func (q *Queries) GetMemo(ctx context.Context, id int64) (Memo, error) {
	row := q.db.QueryRow(ctx, getMemo, id)
	var i Memo
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Content,
		&i.ContentHtml,
		&i.Metadata,
		&i.Pinned,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getMemoTags = `-- name: GetMemoTags :many
SELECT t.id, t.name, t.created_at
FROM tags t
JOIN memo_tags mt ON mt.tag_id = t.id
WHERE mt.memo_id = $1
`

func (q *Queries) GetMemoTags(ctx context.Context, memoID int64) ([]Tag, error) {
	rows, err := q.db.Query(ctx, getMemoTags, memoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tag{}
	for rows.Next() {
		var i Tag
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMemosByDateLabel = `-- name: GetMemosByDateLabel :many
SELECT m.id, m.session_id, m.content, m.content_html, m.metadata, m.pinned,
       m.created_at, m.updated_at, m.deleted_at
FROM memos m
JOIN sessions s ON s.id = m.session_id
WHERE s.date_label = $1
ORDER BY m.created_at
`

func (q *Queries) GetMemosByDateLabel(ctx context.Context, dateLabel pgtype.Date) ([]Memo, error) {
	rows, err := q.db.Query(ctx, getMemosByDateLabel, dateLabel)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Memo{}
	for rows.Next() {
		var i Memo
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Content,
			&i.ContentHtml,
			&i.Metadata,
			&i.Pinned,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMemosBySession = `-- name: GetMemosBySession :many
SELECT id, session_id, content, content_html, metadata, pinned, created_at, updated_at, deleted_at
FROM memos
WHERE session_id = $1
ORDER BY created_at
`

func (q *Queries) GetMemosBySession(ctx context.Context, sessionID int64) ([]Memo, error) {
	rows, err := q.db.Query(ctx, getMemosBySession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Memo{}
	for rows.Next() {
		var i Memo
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Content,
			&i.ContentHtml,
			&i.Metadata,
			&i.Pinned,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStats = `-- name: GetStats :one
SELECT
    (SELECT COUNT(*) FROM memos WHERE deleted_at IS NULL)::int AS total_memos,
    (SELECT COUNT(*) FROM sessions)::int AS total_sessions,
    (SELECT COUNT(DISTINCT date_label) FROM sessions)::int AS active_days,
    (SELECT COALESCE(SUM(total_chars), 0) FROM sessions)::int AS total_chars
`

type GetStatsRow struct {
	TotalMemos    int32 `json:"total_memos"`
	TotalSessions int32 `json:"total_sessions"`
	ActiveDays    int32 `json:"active_days"`
	TotalChars    int32 `json:"total_chars"`
}

func (q *Queries) GetStats(ctx context.Context) (GetStatsRow, error) {
	row := q.db.QueryRow(ctx, getStats)
	var i GetStatsRow
	err := row.Scan(
		&i.TotalMemos,
		&i.TotalSessions,
		&i.ActiveDays,
		&i.TotalChars,
	)
	return i, err
}

const listDeletedMemos = `-- name: ListDeletedMemos :many
SELECT m.id, m.session_id, m.content, m.content_html, m.metadata, m.pinned,
       m.created_at, m.updated_at, m.deleted_at
FROM memos m
WHERE m.deleted_at IS NOT NULL
ORDER BY m.deleted_at DESC
LIMIT $1
`

func (q *Queries) ListDeletedMemos(ctx context.Context, pageLimit int32) ([]Memo, error) {
	rows, err := q.db.Query(ctx, listDeletedMemos, pageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Memo{}
	for rows.Next() {
		var i Memo
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Content,
			&i.ContentHtml,
			&i.Metadata,
			&i.Pinned,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMemos = `-- name: ListMemos :many
SELECT m.id, m.session_id, m.content, m.content_html, m.metadata, m.pinned,
       m.created_at, m.updated_at, m.deleted_at
FROM memos m
WHERE m.deleted_at IS NULL
  AND (m.created_at < $1 OR (m.created_at = $1 AND m.id < $2))
ORDER BY m.created_at DESC, m.id DESC
LIMIT $3
`

type ListMemosParams struct {
	CursorCreatedAt pgtype.Timestamptz `json:"cursor_created_at"`
	CursorID        int64              `json:"cursor_id"`
	PageLimit       int32              `json:"page_limit"`
}

func (q *Queries) ListMemos(ctx context.Context, arg ListMemosParams) ([]Memo, error) {
	rows, err := q.db.Query(ctx, listMemos, arg.CursorCreatedAt, arg.CursorID, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Memo{}
	for rows.Next() {
		var i Memo
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Content,
			&i.ContentHtml,
			&i.Metadata,
			&i.Pinned,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMemosByTag = `-- name: ListMemosByTag :many
SELECT m.id, m.session_id, m.content, m.content_html, m.metadata, m.pinned,
       m.created_at, m.updated_at, m.deleted_at
FROM memos m
JOIN memo_tags mt ON mt.memo_id = m.id
JOIN tags t ON t.id = mt.tag_id
WHERE t.name = $1
  AND m.deleted_at IS NULL
  AND (m.created_at < $2 OR (m.created_at = $2 AND m.id < $3))
ORDER BY m.created_at DESC, m.id DESC
LIMIT $4
`

type ListMemosByTagParams struct {
	TagName         string             `json:"tag_name"`
	CursorCreatedAt pgtype.Timestamptz `json:"cursor_created_at"`
	CursorID        int64              `json:"cursor_id"`
	PageLimit       int32              `json:"page_limit"`
}

func (q *Queries) ListMemosByTag(ctx context.Context, arg ListMemosByTagParams) ([]Memo, error) {
	rows, err := q.db.Query(ctx, listMemosByTag,
		arg.TagName,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Memo{}
	for rows.Next() {
		var i Memo
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Content,
			&i.ContentHtml,
			&i.Metadata,
			&i.Pinned,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMemosByTagFirst = `-- name: ListMemosByTagFirst :many
SELECT m.id, m.session_id, m.content, m.content_html, m.metadata, m.pinned,
       m.created_at, m.updated_at, m.deleted_at
FROM memos m
JOIN memo_tags mt ON mt.memo_id = m.id
JOIN tags t ON t.id = mt.tag_id
WHERE t.name = $1
  AND m.deleted_at IS NULL
ORDER BY m.created_at DESC, m.id DESC
LIMIT $2
`

type ListMemosByTagFirstParams struct {
	TagName   string `json:"tag_name"`
	PageLimit int32  `json:"page_limit"`
}

func (q *Queries) ListMemosByTagFirst(ctx context.Context, arg ListMemosByTagFirstParams) ([]Memo, error) {
	rows, err := q.db.Query(ctx, listMemosByTagFirst, arg.TagName, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Memo{}
	for rows.Next() {
		var i Memo
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Content,
			&i.ContentHtml,
			&i.Metadata,
			&i.Pinned,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMemosFirst = `-- name: ListMemosFirst :many
SELECT m.id, m.session_id, m.content, m.content_html, m.metadata, m.pinned,
       m.created_at, m.updated_at, m.deleted_at
FROM memos m
WHERE m.deleted_at IS NULL
ORDER BY m.created_at DESC, m.id DESC
LIMIT $1
`

func (q *Queries) ListMemosFirst(ctx context.Context, pageLimit int32) ([]Memo, error) {
	rows, err := q.db.Query(ctx, listMemosFirst, pageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Memo{}
	for rows.Next() {
		var i Memo
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Content,
			&i.ContentHtml,
			&i.Metadata,
			&i.Pinned,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMemosSince = `-- name: ListMemosSince :many
SELECT m.id, m.session_id, m.content, m.content_html, m.metadata, m.pinned,
       m.created_at, m.updated_at, m.deleted_at
FROM memos m
WHERE m.deleted_at IS NULL AND m.created_at > $1
ORDER BY m.created_at DESC, m.id DESC
LIMIT $2
`

type ListMemosSinceParams struct {
	Since     pgtype.Timestamptz `json:"since"`
	PageLimit int32              `json:"page_limit"`
}

func (q *Queries) ListMemosSince(ctx context.Context, arg ListMemosSinceParams) ([]Memo, error) {
	rows, err := q.db.Query(ctx, listMemosSince, arg.Since, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Memo{}
	for rows.Next() {
		var i Memo
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Content,
			&i.ContentHtml,
			&i.Metadata,
			&i.Pinned,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPinnedMemos = `-- name: ListPinnedMemos :many
SELECT m.id, m.session_id, m.content, m.content_html, m.metadata, m.pinned,
       m.created_at, m.updated_at, m.deleted_at
FROM memos m
WHERE m.pinned = TRUE AND m.deleted_at IS NULL
ORDER BY m.created_at DESC
`

func (q *Queries) ListPinnedMemos(ctx context.Context) ([]Memo, error) {
	rows, err := q.db.Query(ctx, listPinnedMemos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Memo{}
	for rows.Next() {
		var i Memo
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Content,
			&i.ContentHtml,
			&i.Metadata,
			&i.Pinned,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessions = `-- name: ListSessions :many
SELECT id, started_at, ended_at, date_label, memo_count, total_chars
FROM sessions
WHERE date_label >= $1 AND date_label <= $2
ORDER BY started_at DESC
`

type ListSessionsParams struct {
	FromDate pgtype.Date `json:"from_date"`
	ToDate   pgtype.Date `json:"to_date"`
}

func (q *Queries) ListSessions(ctx context.Context, arg ListSessionsParams) ([]Session, error) {
	rows, err := q.db.Query(ctx, listSessions, arg.FromDate, arg.ToDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.StartedAt,
			&i.EndedAt,
			&i.DateLabel,
			&i.MemoCount,
			&i.TotalChars,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTags = `-- name: ListTags :many
SELECT t.id, t.name, t.created_at, COUNT(mt.memo_id)::int AS memo_count
FROM tags t
JOIN memo_tags mt ON mt.tag_id = t.id
JOIN memos m ON m.id = mt.memo_id AND m.deleted_at IS NULL
GROUP BY t.id
ORDER BY memo_count DESC
`

type ListTagsRow struct {
	ID        int64              `json:"id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	MemoCount int32              `json:"memo_count"`
}

func (q *Queries) ListTags(ctx context.Context) ([]ListTagsRow, error) {
	rows, err := q.db.Query(ctx, listTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTagsRow{}
	for rows.Next() {
		var i ListTagsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.MemoCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const permanentDeleteMemo = `-- name: PermanentDeleteMemo :exec
DELETE FROM memos WHERE id = $1
`

func (q *Queries) PermanentDeleteMemo(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, permanentDeleteMemo, id)
	return err
}

const purgeOldDeletedMemos = `-- name: PurgeOldDeletedMemos :exec
DELETE FROM memos
WHERE deleted_at IS NOT NULL
  AND deleted_at < NOW() - INTERVAL '30 days'
`

func (q *Queries) PurgeOldDeletedMemos(ctx context.Context) error {
	_, err := q.db.Exec(ctx, purgeOldDeletedMemos)
	return err
}

const restoreMemo = `-- name: RestoreMemo :exec
UPDATE memos SET deleted_at = NULL WHERE id = $1 AND deleted_at IS NOT NULL
`

func (q *Queries) RestoreMemo(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, restoreMemo, id)
	return err
}

const searchMemos = `-- name: SearchMemos :many
SELECT m.id, m.session_id, m.content, m.content_html, m.metadata, m.pinned,
       m.created_at, m.updated_at, m.deleted_at
FROM memos m
WHERE m.content ILIKE '%' || $1 || '%'
  AND m.deleted_at IS NULL
  AND (m.created_at < $2 OR (m.created_at = $2 AND m.id < $3))
ORDER BY m.created_at DESC, m.id DESC
LIMIT $4
`

type SearchMemosParams struct {
	Query           pgtype.Text        `json:"query"`
	CursorCreatedAt pgtype.Timestamptz `json:"cursor_created_at"`
	CursorID        int64              `json:"cursor_id"`
	PageLimit       int32              `json:"page_limit"`
}

func (q *Queries) SearchMemos(ctx context.Context, arg SearchMemosParams) ([]Memo, error) {
	rows, err := q.db.Query(ctx, searchMemos,
		arg.Query,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Memo{}
	for rows.Next() {
		var i Memo
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Content,
			&i.ContentHtml,
			&i.Metadata,
			&i.Pinned,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchMemosFirst = `-- name: SearchMemosFirst :many
SELECT m.id, m.session_id, m.content, m.content_html, m.metadata, m.pinned,
       m.created_at, m.updated_at, m.deleted_at
FROM memos m
WHERE m.content ILIKE '%' || $1 || '%'
  AND m.deleted_at IS NULL
ORDER BY m.created_at DESC, m.id DESC
LIMIT $2
`

type SearchMemosFirstParams struct {
	Query     pgtype.Text `json:"query"`
	PageLimit int32       `json:"page_limit"`
}

func (q *Queries) SearchMemosFirst(ctx context.Context, arg SearchMemosFirstParams) ([]Memo, error) {
	rows, err := q.db.Query(ctx, searchMemosFirst, arg.Query, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Memo{}
	for rows.Next() {
		var i Memo
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Content,
			&i.ContentHtml,
			&i.Metadata,
			&i.Pinned,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteMemo = `-- name: SoftDeleteMemo :exec
UPDATE memos SET deleted_at = NOW() WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteMemo(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, softDeleteMemo, id)
	return err
}

const togglePin = `-- name: TogglePin :one
UPDATE memos SET pinned = NOT pinned
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, session_id, content, content_html, metadata, pinned, created_at, updated_at, deleted_at
`

func (q *Queries) TogglePin(ctx context.Context, id int64) (Memo, error) {
	row := q.db.QueryRow(ctx, togglePin, id)
	var i Memo
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Content,
		&i.ContentHtml,
		&i.Metadata,
		&i.Pinned,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateMemo = `-- name: UpdateMemo :one
UPDATE memos SET content = $2, content_html = $3
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, session_id, content, content_html, metadata, pinned, created_at, updated_at, deleted_at
`

type UpdateMemoParams struct {
	ID          int64  `json:"id"`
	Content     string `json:"content"`
	ContentHtml string `json:"content_html"`
}

func (q *Queries) UpdateMemo(ctx context.Context, arg UpdateMemoParams) (Memo, error) {
	row := q.db.QueryRow(ctx, updateMemo, arg.ID, arg.Content, arg.ContentHtml)
	var i Memo
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Content,
		&i.ContentHtml,
		&i.Metadata,
		&i.Pinned,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateSessionStats = `-- name: UpdateSessionStats :exec
UPDATE sessions
SET memo_count = memo_count + 1,
    total_chars = total_chars + $1::int,
    ended_at = $2
WHERE id = $3
`

type UpdateSessionStatsParams struct {
	Chars int32              `json:"chars"`
	Now   pgtype.Timestamptz `json:"now"`
	ID    int64              `json:"id"`
}

func (q *Queries) UpdateSessionStats(ctx context.Context, arg UpdateSessionStatsParams) error {
	_, err := q.db.Exec(ctx, updateSessionStats, arg.Chars, arg.Now, arg.ID)
	return err
}

const upsertDailyReport = `-- name: UpsertDailyReport :one
INSERT INTO daily_reports (report_date, session_count, total_memos, total_chars, chars_per_minute, active_minutes, hourly_distribution)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (report_date) DO UPDATE SET
    session_count = EXCLUDED.session_count,
    total_memos = EXCLUDED.total_memos,
    total_chars = EXCLUDED.total_chars,
    chars_per_minute = EXCLUDED.chars_per_minute,
    active_minutes = EXCLUDED.active_minutes,
    hourly_distribution = EXCLUDED.hourly_distribution
RETURNING id, report_date, session_count, total_memos, total_chars,
          chars_per_minute, active_minutes, hourly_distribution, created_at
`

type UpsertDailyReportParams struct {
	ReportDate         pgtype.Date     `json:"report_date"`
	SessionCount       int32           `json:"session_count"`
	TotalMemos         int32           `json:"total_memos"`
	TotalChars         int32           `json:"total_chars"`
	CharsPerMinute     pgtype.Float8   `json:"chars_per_minute"`
	ActiveMinutes      int32           `json:"active_minutes"`
	HourlyDistribution json.RawMessage `json:"hourly_distribution"`
}

func (q *Queries) UpsertDailyReport(ctx context.Context, arg UpsertDailyReportParams) (DailyReport, error) {
	row := q.db.QueryRow(ctx, upsertDailyReport,
		arg.ReportDate,
		arg.SessionCount,
		arg.TotalMemos,
		arg.TotalChars,
		arg.CharsPerMinute,
		arg.ActiveMinutes,
		arg.HourlyDistribution,
	)
	var i DailyReport
	err := row.Scan(
		&i.ID,
		&i.ReportDate,
		&i.SessionCount,
		&i.TotalMemos,
		&i.TotalChars,
		&i.CharsPerMinute,
		&i.ActiveMinutes,
		&i.HourlyDistribution,
		&i.CreatedAt,
	)
	return i, err
}

const upsertTag = `-- name: UpsertTag :one
INSERT INTO tags (name) VALUES ($1)
ON CONFLICT (name) DO UPDATE SET name = EXCLUDED.name
RETURNING id, name, created_at
`

func (q *Queries) UpsertTag(ctx context.Context, name string) (Tag, error) {
	row := q.db.QueryRow(ctx, upsertTag, name)
	var i Tag
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}
